spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
    show-sql: true
  jwt:
    secret: kghobnakghwoigabsdlkbghaoigqhegowebnhlkwehgaoiwehtoaweqnbzoiwnyzbvwow
    expiration-time: 86400000

logging:
  level:
    org:
      hibernate: debug