name: Backend CI

on:
  pull_request:
    branches: [ "develop", "week**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Set YML
      env:
        DATA_KEY_YML: ${{ secrets.APPLICATION_DATA_YML }}
      run: |
        echo $DATA_KEY_YML | base64 --decode > src/main/resources/application-data.yml
        find src/main/resources
        wc -c src/main/resources/application-data.yml

    - name: Build with Gradle Wrapper
      run: ./gradlew build
